apiVersion: v1
kind: Service
metadata:
  name: open5gs-nssf-svc-pool
  namespace: open5gs-ueransim
  labels:
    ngc-mode: nssf
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    ngc-mode: nssf
