apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-nssf-config
  namespace: open5gs-ueransim
  labels:
    ngc-mode: nssf
data:
  nssf.yaml: |
    nssf:
      sbi:
        - dev: eth0
          port: 7777
      nsi:
        - name: open5gs-nrf-svc-pool
        #- addr: ::1
          port: 7777
          s_nssai:
            sst: 1
            #sd: 1

    nrf:
        sbi:
          - name: open5gs-nrf-svc-pool
            port: 7777
