apiVersion: v1
kind: Service
metadata:
  name: open5gs-amf-svc-pool
  namespace: open5gs-ueransim
  labels:
    ngc-mode: amf
spec:
  type: ClusterIP
  #clusterIP: None
  ports:
  - name: sbi
    port: 7001
    protocol: TCP
  - name: ngap 
    port: 38412
    protocol: SCTP

  publishNotReadyAddresses: true
  selector:
    ngc-mode: amf
