version: '3'
services: 
  gnb1:
    image: ueransimfordocker:3.2.2
    container_name: gnb1
    command: 
      - gnb
    environment:
      AMF_HOSTNAME: amf
      GNB_HOSTNAME: gnb1
      MCC: '001'
      MNC: '01'
      SST: '1'
      SD: '1'
      GNB_ADDR: '10.178.70.77'
      AMF_ADDR: '10.178.70.74'
    network_mode: "host"

