version: '3'
services: 
  gnb1:
    image: ueransimfordocker:3.2.2
    container_name: gnb1
    command: 
      - gnb
    cap_add:
      - all
    privileged: true
    environment:
      AMF_HOSTNAME: amf
      GNB_HOSTNAME: gnb1
      MCC: '999'
      MNC: '70'
      SST: '1'
      SD: '1'
      GNB_ADDR: '172.31.2.6'
      AMF_ADDR: '172.30.8.118'
      NCI: '0x0000000010'
    network_mode: "host"

