version: '3'
services: 
  ue1:
    image: ueransimfordocker:3.2.2
    container_name: ue1
    command: 
      - ue
    cap_add:
      - all
    privileged: true
    environment:
      GNB_HOSTNAME: gnb1
      APN: internet
      MSISDN: '0000000001'
      KEY: '465B5CE8B199B49FAA5F0A2EE238A6BC'
      OP_TYPE: OPC
      OP: 'E8ED289DEBA952E4283B54E88E6183CA'
      MCC: '001'
      MNC: '01'
      SST: '1'
      SD: '1'
      GNB_ADDR: '10.178.70.77'
    network_mode: "host"
    
