version: '3'
services: 
  ue1:
    image: ueransimfordocker:3.2.2
    container_name: ue1
    command: 
      - ue
    cap_add:
      - all
    privileged: true
    environment:
      GNB_HOSTNAME: gnb1
      APN: internet.lguplus.co.kr
      MSISDN: '0000054044'
      KEY: 'D77E153F69F5462F40A0E15F5F8BFB91'
      OP_TYPE: OPC
      OP: 'CE231560DB6DBC0C17EFAE7BB22BEF25'
      MCC: '999'
      MNC: '70'
      SST: '1'
      SD: '1'
      GNB_ADDR: '172.31.2.6'
    network_mode: "host"
    
