apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-udm-config
  namespace: open5gs-ueransim
  labels:
    ngc-mode: udm
data:
  udm.yaml: |
    udm:
      sbi:
        - dev: eth0
          port: 7777

    nrf:
        sbi:
          - name: open5gs-nrf-svc-pool
            port: 7777
