apiVersion: v1
kind: Service
metadata:
  name: open5gs-pcf-svc-pool
  namespace: open5gs-ueransim
  labels:
    ngc-mode: pcf
spec:
  type: ClusterIP
  #clusterIP: None
  ports:
  - name: sbi
    port: 7005
    protocol: TCP

  publishNotReadyAddresses: true
  selector:
    ngc-mode: pcf
