apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-pcf-config
  namespace: open5gs-ueransim
  labels:
    ngc-mode: pcf
data:
  pcf.yaml: |
    pcf:
      sbi:
        - dev: eth0
          port: 7777

    nrf:
        sbi:
          - name: open5gs-nrf-svc-pool
            port: 7777
