apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-ausf-config
  namespace: open5gs-ueransim
  labels:
    ngc-mode: ausf
data:
  ausf.yaml: |
    ausf:
      sbi:
        - dev: eth0
          port: 7777

    nrf:
        sbi:
          - name: open5gs-nrf-svc-pool
            port: 7777
