apiVersion: v1
kind: Service
metadata:
  name: open5gs-ausf-svc-pool
  namespace: open5gs-ueransim
  labels:
    ngc-mode: ausf
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    ngc-mode: ausf
