apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-bsf-config
  namespace: open5gs-ueransim
  labels:
    ngc-mode: bsf
data:
  bsf.yaml: |
    bsf:
      sbi:
        - dev: eth0
          port: 7777

    nrf:
        sbi:
          - name: open5gs-nrf-svc-pool
            port: 7777
