apiVersion: v1
kind: Service
metadata:
  name: open5gs-upf-svc-pool
  namespace: open5gs-ueransim
  labels:
    ngc-mode: upf
spec:
  type: ClusterIP
  #clusterIP: None
  ports:
  - name: gtp-u
    port: 2152
    protocol: UDP
  - name: pfcp
    port: 8805
    protocol: UDP

  publishNotReadyAddresses: true
  selector:
    ngc-mode: upf
