apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-upf-config
  namespace: open5gs-ueransim
  labels:
    ngc-mode: upf
data:
  upf.yaml: |
    logger:
      level: info

    upf:
        pfcp:
          dev: eth0
        gtpu:
          dev: eth0
          #advertise_name: "open5gs-upf-svc-pool"
          advertise: 10.178.70.74
        subnet:
          #- addr: 10.45.0.1/16
          - addr: 100.45.0.1/16
            dnn: internet    
            dev: ogstun
    smf:
        pfcp:
          #- addr: 10.96.100.104
          - name: open5gs-smf-svc-pool
