apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: upf-n3
  namespace: open5gs-ueransim
spec:
  config: |
    { 
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "ens3",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "10.178.70.79/21",
            "gateway": "10.178.64.1"

          }
        ]
      }
    }
