apiVersion: v1
kind: Service
metadata:
  name: open5gs-upf-svc-pool
  namespace: open5gs-ueransim
  labels:
    ngc-mode: upf
spec:
  type: ClusterIP
#  clusterIP: 10.96.100.107
  clusterIP: None
  selector:
    ngc-mode: upf
