apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-nrf-config
  namespace: open5gs-ueransim
  labels:
    ngc-mode: nrf
data:
  nrf.yaml: |
    nrf:
        sbi:
          - dev: eth0
            port: 7777
