apiVersion: v1
kind: Service
metadata:
  name: open5gs-nrf-svc-pool
  namespace: open5gs-ueransim
  labels:
    ngc-mode: nrf
spec:
  type: ClusterIP
  #clusterIP: 10.96.100.110
  clusterIP: None
  selector:
    ngc-mode: nrf
#  ports:
#    - name: nrf-sbi-tcp
#      protocol: TCP
#      port: 7777
#    - name: nrf-sbi-udp
#      protocol: UDP
#      port: 7777

