apiVersion: v1
kind: Service
metadata:
  name: open5gs-nrf-svc-pool
  namespace: open5gs-ueransim
  labels:
    ngc-mode: nrf
spec:
  type: ClusterIP  
  #clusterIP: None
  ports:
  - name: sbi
    port: 7777
    protocol: TCP

  publishNotReadyAddresses: true
  selector:
    ngc-mode: nrf


