apiVersion: v1
kind: Service
metadata:
  name: open5gs-nrf-svc-pool
#  namespace: open5gs
  labels:
    nr-mode: nrf
spec:
  selector:
    nr-mode: nrf
  ports:
    - protocol: TCP
      port: 7777   
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-nrf
#  namespace: open5gs
  labels:
    nr-mode: nrf
spec:
  replicas: 1
  selector:
    matchLabels:
      nr-mode: nrf
  template:
    metadata:
      labels:
        nr-mode: nrf
    spec:   
      containers:
        - name: nrf
          image: ohyoungili/open5gs:2.3.0          
          command: ["open5gs-nrfd", "-c", "/opt/open5gs/etc/open5gs/nrf.yaml"]
          #command: ["/bin/bash"]
          #args: ["-c", "sleep 1000"]
          volumeMounts:
            - name: open5gs-nrf-config
#              mountPath: /open5gs/config-map/nrf.yaml
              mountPath: /opt/open5gs/etc/open5gs/nrf.yaml
              subPath: "nrf.yaml"
      volumes:
        - name: open5gs-nrf-config
          configMap:
            name: open5gs-nrf-config
