apiVersion: v1
kind: Service
metadata:
  name: open5gs-smf-svc-pool
  namespace: open5gs-ueransim
  labels:
    ngc-mode: smf
spec:
  type: ClusterIP
  clusterIP: 10.96.100.104
#  clusterIP: None
  selector:
    ngc-mode: smf
  ports:
    - name: smf-sbi-tcp
      protocol: TCP
      port: 7777
    - name: smf-sbi-udp
      protocol: UDP
      port: 7777
