apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-smf-config
  namespace: open5gs-ueransim
  labels:
    ngc-mode: smf
data:
  smf.yaml: |
    smf:
        sbi:
          - dev: eth0
            port: 7777
        gtpc:
          dev: eth0
        gtpu:
          dev: eth0
        pfcp:
          dev: eth0
        subnet:
          - addr: 10.45.0.1/16
            dnn: internet
        dns:
          - 8.8.8.8
          - 8.8.4.4
        mtu: 1400
        freeDiameter: /opt/open5gs/etc/freeDiameter/diameter-smf.conf

    nrf:
      sbi:
        - addr: 10.96.100.110
          port: 7777
       # - name: open5gs-nrf-svc-pool.open5gs-ueransim
       #   port: 7777

    upf:
      pfcp:
        - addr: 10.96.100.107
          dnn: interenet
        #- name: open5gs-upf-svc-pool.open5gs-ueransim
        #  dnn: internet
