#apiVersion: v1
#kind: Service
#metadata:
#  name: open5gs-smf-svc-pool
#  namespace: open5gs-ueransim
#  labels:
#    ngc-mode: smf
#spec:
#  clusterIP: None
##  ports:
##  - name: gx
##    port: 3868
##    protocol: TCP  
##  - name: pfcp
##    port: 3868
##    protocol: UDP
#  selector:  
#    ngc-mode: smf        
#---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: open5gs-smf
  namespace: open5gs-ueransim
  labels:
    ngc-mode: smf
spec:
  replicas: 1
  serviceName: "open5gs-smf-svc-pool"
  selector:
    matchLabels:
      ngc-mode: smf
  template:
    metadata:
      labels:
        ngc-mode: smf
    spec:
      containers:
        - name: smf
          image: ohyoungili/open5gs:2.3.0
          imagePullPolicy: IfNotPresent         
          #command: ["open5gs-smfd", "-c", "/opt/open5gs/etc/open5gs/smf.yaml"]
          command: ["/bin/sh", "-c"]
          args:
            - sleep 10;
              open5gs-smfd -c /opt/open5gs/etc/open5gs/smf.yaml;
          volumeMounts:
          - name: open5gs-smf-config
            mountPath: /opt/open5gs/etc/open5gs/smf.yaml
            subPath: "smf.yaml"
          - name: open5gs-smf-diameter
            mountPath: /opt/open5gs/etc/freeDiameter/diameter-smf.conf
            subPath: "diameter-smf.conf"               
      volumes:
        - name: open5gs-smf-config
          configMap:
            name: open5gs-smf-config
        - name: open5gs-smf-diameter
          configMap:
            name: open5gs-smf-diameter
