apiVersion: v1
kind: Service
metadata:
  name: open5gs-webui
  namespace: open5gs-ueransim
  labels:
    ngc-mode: webui
spec:
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      nodePort: 30000
  selector:
    ngc-mode: webui
